package main.data_access.player;

import main.use_case.characterSelectionScreen.CharacterSelectionScreenDataAccessInterface;

public class InMemoryCharacterDataAccess implements CharacterSelectionScreenDataAccessInterface {
}
