package main.data_access.player;

import main.use_case.character_selection_screen.CharacterSelectionScreenDataAccessInterface;

public class InMemoryCharacterDataAccess implements CharacterSelectionScreenDataAccessInterface {
}
