package main.data_access.Player;

import main.use_case.CharacterSelectionScreen.CharacterSelectionScreenDataAccessInterface;

public class InMemoryCharacterDataAccess implements CharacterSelectionScreenDataAccessInterface {
}
