package main.data_access.StockMarket;

import main.use_case.characterSelectionScreen.CharacterSelectionScreenDataAccessInterface;

public class InMemoryCharacterDataAccess implements CharacterSelectionScreenDataAccessInterface {
}
